"""add_is_absent_to_ballot_submissions

Revision ID: 0b8d45b3ee02
Revises: bff4aff58e97
Create Date: 2026-03-28 18:36:14.714688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b8d45b3ee02'
down_revision: Union[str, Sequence[str], None] = 'bff4aff58e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ballot_submissions', sa.Column('is_absent', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index(op.f('ix_ballot_submissions_gm_email'), table_name='ballot_submissions')
    op.drop_index(op.f('ix_votes_gm_email'), table_name='votes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_votes_gm_email'), 'votes', ['general_meeting_id', 'voter_email'], unique=False)
    op.create_index(op.f('ix_ballot_submissions_gm_email'), 'ballot_submissions', ['general_meeting_id', 'voter_email'], unique=False)
    op.drop_column('ballot_submissions', 'is_absent')
    # ### end Alembic commands ###
